name: Data processing workflow

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Set up Google API credentials
      run: |
        echo "${{ secrets.GOOGLE_API }}" > credentials.json

    - name: Run data processing script
      run: python3 data_processing.py

    - name: Show report
      run: cat report.txt

    - name: Display logs
      run: cat log.txt
