name: Run Analysis

on:
  push:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the analysis
      run: python main.py

    - name: Display the results from evaluation_best_model.txt
      run: cat evaluation_best_model.txt

    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: results
        path: "**/*.png, **/*.txt"
        if-no-files-found: warn
